import { invoke } from "@tauri-apps/api/core";
import { clampRecorderDate, createDateBoundDebounce, nextRecorderToday, rebaseConflictCandidate, resolveVersionedPayloadConflict } from "@capture/recorder-kit";
import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import type { FoodEntry, FoodPayload, FoodRecord } from "../../../web/src/lib/food-record";
import { emptyFoodPayload, isFoodPayloadReady } from "../../../web/src/lib/food-record";
import type { FoodLibraryEntry, FoodLibraryPayload, FoodLibraryRecord } from "../../../web/src/lib/food-library";
import { emptyFoodLibrary } from "../../../web/src/lib/food-library";
import type { CapturePageDefinition, CapturePageProps } from "./types";

const KEY = "capture.desktop.food.v1";
type Local = { payload: FoodPayload; revision: number | null; pending: boolean; clientUpdatedAt: string; conflict?: { cloud: FoodRecord | null } };
type Cache = Record<string, Local>;
type SaveResult<T> = { record: T | null; conflict: boolean };
function taipeiDate() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const value = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${value.year}-${value.month}-${value.day}`; }
function read(): Cache { try { return JSON.parse(localStorage.getItem(KEY) ?? "{}"); } catch { return {}; } }
function write(value: Cache) { try { localStorage.setItem(KEY, JSON.stringify(value)); } catch { /* memory remains */ } }
function numeric(value: string) { return value === "" ? null : Number(value); }

function FoodPage({ requestModeChange }: CapturePageProps) {
  const [today, setToday] = useState(taipeiDate); const [date, setDate] = useState(today);
  const [local, setLocal] = useState<Local>(() => read()[today] ?? { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() });
  const [history, setHistory] = useState<FoodRecord[]>([]); const [issue, setIssue] = useState(false);
  const [library, setLibrary] = useState<FoodLibraryPayload>(emptyFoodLibrary); const [libraryRevision, setLibraryRevision] = useState<number | null>(null); const [libraryConflict, setLibraryConflict] = useState<{ local: FoodLibraryPayload; cloud: FoodLibraryRecord | null } | null>(null); const [libraryOpen, setLibraryOpen] = useState(false);
  const localRef = useRef(local); const dateRef = useRef(date); const todayRef = useRef(today);
  const syncDebounceRef = useRef<ReturnType<typeof createDateBoundDebounce<Local>> | null>(null);
  syncDebounceRef.current ??= createDateBoundDebounce<Local>({ delayMs: 800, schedule: (callback, delayMs) => window.setTimeout(callback, delayMs), cancel: (handle) => window.clearTimeout(handle as number) });
  useEffect(() => { if (!libraryConflict) return; resolveLibraryConflict(window.confirm("食物庫已在另一台裝置更新。確定保留本機版本；取消使用雲端版本。") ? "local" : "cloud"); }, [libraryConflict]);
  const editable = date === today;
  const publish = useCallback((targetDate: string, next: Local) => { if (targetDate === dateRef.current) { localRef.current = next; setLocal(next); } const values = read(); values[targetDate] = next; write(values); }, []);
  const syncingDates = useRef(new Set<string>());
  const sync = useCallback(async (targetDate: string, candidate = localRef.current) => { if (!candidate.pending || candidate.conflict || !isFoodPayloadReady(candidate.payload)) return;
    if (syncingDates.current.has(targetDate)) return;
    syncingDates.current.add(targetDate); try { const result = await invoke<SaveResult<FoodRecord>>("save_food_record", { input: { journalDate: targetDate, payload: candidate.payload, expectedRevision: candidate.revision, clientUpdatedAt: candidate.clientUpdatedAt } }); if (result.conflict) { const current = read()[targetDate] ?? candidate; publish(targetDate, { ...current, conflict: { cloud: result.record } }); setIssue(true); return; } const current = read()[targetDate] ?? candidate; if (current.clientUpdatedAt === candidate.clientUpdatedAt) publish(targetDate, { ...current, revision: result.record?.revision ?? null, pending: false, conflict: undefined }); else { const next = { ...current, revision: result.record?.revision ?? null }; publish(targetDate, next); syncDebounceRef.current?.queue(targetDate, next, sync); } setIssue(false); } catch { setIssue(true); } finally { syncingDates.current.delete(targetDate); } }, [publish]);
  const mutate = useCallback((change: (payload: FoodPayload) => void) => { const payload = structuredClone(localRef.current.payload); change(payload); const next = { ...localRef.current, payload, pending: true, clientUpdatedAt: new Date().toISOString() }; const targetDate = dateRef.current; publish(targetDate, next); syncDebounceRef.current?.queue(targetDate, next, sync); }, [publish, sync]);
  const load = useCallback(async (targetDate: string) => { targetDate = clampRecorderDate(targetDate, todayRef.current); dateRef.current = targetDate; setDate(targetDate); const cached = read()[targetDate]; publish(targetDate, cached ?? { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() }); if (cached?.pending) void sync(targetDate, cached); try { const record = await invoke<FoodRecord | null>("get_food_record", { journalDate: targetDate }); if (!read()[targetDate]?.pending) publish(targetDate, record ? { payload: record.payload, revision: record.revision, pending: false, clientUpdatedAt: record.updatedAt } : { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() }); setIssue(false); } catch { if (!cached) setIssue(true); } }, [publish, sync]);
  useEffect(() => { void load(todayRef.current); void invoke<FoodRecord[]>("list_food_records").then(setHistory).catch(() => setIssue(true)); void invoke<FoodLibraryRecord | null>("get_food_library").then((record) => { setLibrary(record?.payload ?? emptyFoodLibrary()); setLibraryRevision(record?.revision ?? null); }).catch(() => setIssue(true)); }, [load]);
  useEffect(() => { const retryPending = () => { for (const [targetDate, candidate] of Object.entries(read())) if (candidate.pending) void sync(targetDate, candidate); }; window.addEventListener("online", retryPending); return () => { window.removeEventListener("online", retryPending); syncDebounceRef.current?.cancel(); }; }, [sync]);
  useEffect(() => { const id = window.setInterval(() => { const nextToday = nextRecorderToday(todayRef.current, taipeiDate()); if (!nextToday) return; const previousDate = dateRef.current; const previous = read()[previousDate] ?? localRef.current; if (previous.pending) void sync(previousDate, previous); todayRef.current = nextToday; setToday(nextToday); void load(nextToday); }, 30_000); return () => window.clearInterval(id); }, [load, sync]);
  const recent = useMemo(() => { const values = library.entries.filter((entry) => !entry.archived).sort((left, right) => left.order - right.order); for (const record of history) for (const entry of [...record.payload.entries].reverse()) if (!values.some((item) => item.name.toLocaleLowerCase() === entry.name.toLocaleLowerCase())) values.push({ id: entry.libraryEntryId ?? entry.id, name: entry.name, quantity: entry.quantity, unit: entry.unit, calories: entry.calories, proteinGrams: entry.proteinGrams, order: values.length, archived: false }); return values.slice(0, 6); }, [history, library]);
  const totals = local.payload.entries.reduce((value, entry) => ({ calories: value.calories + (entry.calories ?? 0), protein: value.protein + (entry.proteinGrams ?? 0) }), { calories: 0, protein: 0 });
  function add(source?: FoodLibraryEntry) { mutate((payload) => payload.entries.push({ id: crypto.randomUUID(), libraryEntryId: source?.id, name: source?.name ?? "", quantity: source?.quantity ?? null, unit: source?.unit ?? "份", calories: source?.calories ?? null, proteinGrams: source?.proteinGrams ?? null, note: "", occurredAt: new Date().toISOString() })); }
  function update(id: string, change: (entry: FoodEntry) => void) { mutate((payload) => { const target = payload.entries.find((entry) => entry.id === id); if (target) change(target); }); }
  async function saveLibrary(next: FoodLibraryPayload, expectedRevision = libraryRevision) { setLibrary(next); try { const result = await invoke<SaveResult<FoodLibraryRecord>>("save_food_library", { input: { payload: next, expectedRevision } }); if (result.conflict) { setLibraryConflict({ local: structuredClone(next), cloud: result.record }); setIssue(true); return; } setLibrary(result.record?.payload ?? next); setLibraryRevision(result.record?.revision ?? expectedRevision); setLibraryConflict(null); setIssue(false); } catch { setIssue(true); } }
  function resolveLibraryConflict(choice: "cloud" | "local") { if (!libraryConflict) return; const resolution = resolveVersionedPayloadConflict(libraryConflict.local, libraryConflict.cloud, choice, emptyFoodLibrary()); setLibrary(resolution.payload); setLibraryRevision(resolution.revision); setLibraryConflict(null); setIssue(resolution.retry); if (resolution.retry) void saveLibrary(resolution.payload, resolution.revision); }
  function ensureLibrary(entry: FoodEntry) { const entryName = entry.name.trim(); if (!entryName || entry.libraryEntryId) return; const existing = library.entries.find((item) => item.name.toLocaleLowerCase() === entryName.toLocaleLowerCase()); const item = existing ?? { id: crypto.randomUUID(), name: entryName, quantity: entry.quantity, unit: entry.unit, calories: entry.calories, proteinGrams: entry.proteinGrams, order: library.entries.length, archived: false }; if (!existing) void saveLibrary({ ...library, entries: [...library.entries, item] }); update(entry.id, (target) => { target.libraryEntryId = item.id; }); }
  function used(entry: FoodLibraryEntry) { return history.some((record) => record.payload.entries.some((food) => food.libraryEntryId === entry.id || (!food.libraryEntryId && food.name.toLocaleLowerCase() === entry.name.toLocaleLowerCase()))); }
  function useCloudVersion() { const cloud = localRef.current.conflict?.cloud; const next: Local = cloud ? { payload: cloud.payload, revision: cloud.revision, pending: false, clientUpdatedAt: cloud.updatedAt } : { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() }; publish(date, next); setIssue(false); }
  function keepLocalVersion() { const current = localRef.current; if (!current.conflict) return; const { conflict, ...withoutConflict } = current; const next = rebaseConflictCandidate(withoutConflict, conflict.cloud?.revision ?? null); publish(date, next); setIssue(false); void sync(date, next); }
  function keys(event: KeyboardEvent<HTMLElement>) { if (event.ctrlKey && (event.key === "ArrowLeft" || event.key === "ArrowRight")) { event.preventDefault(); requestModeChange(event.key === "ArrowLeft" ? -1 : 1); } }
  return <main className="desktopFood viewEnter" tabIndex={0} onKeyDown={keys}>
    <header><label>{date.slice(5).replace("-", ".")}<input type="date" max={today} value={date} onChange={(event) => void load(event.target.value)} /></label><strong>飲食紀錄</strong><i>{issue ? "尚未同步" : local.pending ? "儲存中" : "已儲存"}</i></header>
    {local.conflict ? <div className="specialConflict" role="alert"><span>雲端已有較新的飲食內容</span><button type="button" onClick={useCloudVersion}>保留雲端</button><button type="button" onClick={keepLocalVersion}>保留這台</button></div> : null}
    <section>
      <div className="desktopFoodSection"><h2>今日總計</h2><div className="desktopFoodTotals"><span><strong>{totals.calories}</strong> kcal</span><span>蛋白質 <strong>{totals.protein}</strong> g</span></div></div>
      <div className="desktopFoodSection"><h2>新增飲食</h2><nav>{recent.map((entry) => <button key={entry.id} disabled={!editable} onClick={() => add(entry)}>＋ {entry.name}</button>)}<button className="desktopPrimaryAction" disabled={!editable} onClick={() => add()}>＋ 新增食物</button><button onClick={() => setLibraryOpen((open) => !open)}>{libraryOpen ? "收起管理" : "目標與常用食物"}</button></nav></div>
      {libraryOpen ? <div className="desktopFoodSection desktopFoodSettings"><h2>目標與常用食物管理</h2><div className="desktopFoodTargets"><label>熱量目標<input aria-label="熱量目標" type="number" value={local.payload.calorieTarget ?? ""} disabled={!editable} onChange={(event) => mutate((payload) => { payload.calorieTarget = numeric(event.target.value); })} /></label><label>蛋白質目標<input aria-label="蛋白質目標" type="number" value={local.payload.proteinTargetGrams ?? ""} disabled={!editable} onChange={(event) => mutate((payload) => { payload.proteinTargetGrams = numeric(event.target.value); })} /></label></div><div className="desktopFoodLibrary">{library.entries.slice().sort((left, right) => left.order - right.order).map((entry, index, entries) => <div key={entry.id} className={entry.archived ? "archived" : ""}><input value={entry.name} onChange={(event) => setLibrary((current) => ({ ...current, entries: current.entries.map((item) => item.id === entry.id ? { ...item, name: event.target.value } : item) }))} onBlur={(event) => { const entryName = event.target.value.trim(); if (entryName) void saveLibrary({ ...library, entries: library.entries.map((item) => item.id === entry.id ? { ...item, name: entryName } : item) }); }} /><button disabled={index === 0} onClick={() => { const next = entries.slice(); [next[index - 1], next[index]] = [next[index], next[index - 1]]; void saveLibrary({ ...library, entries: next.map((item, order) => ({ ...item, order })) }); }}>上移</button><button disabled={index === entries.length - 1} onClick={() => { const next = entries.slice(); [next[index], next[index + 1]] = [next[index + 1], next[index]]; void saveLibrary({ ...library, entries: next.map((item, order) => ({ ...item, order })) }); }}>下移</button><button onClick={() => void saveLibrary({ ...library, entries: library.entries.map((item) => item.id === entry.id ? { ...item, archived: !item.archived } : item) })}>{entry.archived ? "取消封存" : "封存"}</button>{!used(entry) ? <button onClick={() => void saveLibrary({ ...library, entries: library.entries.filter((item) => item.id !== entry.id).map((item, order) => ({ ...item, order })) })}>刪除</button> : <span />}</div>)}</div></div> : null}
      <div className="desktopFoodSection desktopFoodRecords"><h2>今日紀錄 <small>{local.payload.entries.length} 筆</small></h2>{local.payload.entries.length === 0 ? <p>還沒有紀錄。</p> : null}{local.payload.entries.map((entry) => <article key={entry.id}><div><input className="desktopFoodName" placeholder="食物名稱" value={entry.name} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.name = event.target.value; })} onBlur={() => ensureLibrary(entry)} /><small>{new Intl.DateTimeFormat("zh-TW", { timeZone: "Asia/Taipei", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(entry.occurredAt))}</small>{editable ? <button onClick={() => mutate((payload) => { payload.entries = payload.entries.filter((item) => item.id !== entry.id); })}>移除</button> : null}</div><div className="desktopFoodFields">{([['quantity','量'],['unit','單位'],['calories','kcal'],['proteinGrams','蛋白質 g']] as const).map(([key, label]) => <label key={key}>{label}<input type={key === "unit" ? "text" : "number"} value={entry[key] ?? ""} disabled={!editable} onChange={(event) => update(entry.id, (item) => { if (key === "unit") item.unit = event.target.value; else item[key] = numeric(event.target.value); })} /></label>)}</div><textarea placeholder="註記" value={entry.note} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.note = event.target.value; })} /></article>)}</div>
    </section>
  </main>;
}
export default { id: "food", Component: FoodPage } satisfies CapturePageDefinition;
