"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { FoodEntry, FoodPayload, FoodRecord } from "../lib/food-record";
import { emptyFoodPayload, isFoodPayloadReady } from "../lib/food-record";
import { toTaipeiDate } from "../lib/special-record";
import { shiftJournalDate } from "./journal-session";
import { ModuleRail, type CaptureModule } from "./module-rail";
import type { FoodLibraryEntry, FoodLibraryPayload, FoodLibraryRecord } from "../lib/food-library";
import { emptyFoodLibrary } from "../lib/food-library";
import { clampRecorderDate, createDateBoundDebounce, rebaseConflictCandidate } from "@capture/recorder-kit";

const CACHE_KEY = "capture.food.v1";
type LocalFood = { payload: FoodPayload; revision: number | null; pending: boolean; clientUpdatedAt: string; conflict?: { cloud: FoodRecord | null } };
type Cache = Record<string, LocalFood>;
function cache(): Cache { try { return JSON.parse(localStorage.getItem(CACHE_KEY) ?? "{}"); } catch { return {}; } }
function persist(values: Cache) { try { localStorage.setItem(CACHE_KEY, JSON.stringify(values)); } catch { /* memory remains */ } }
function number(value: string) { return value === "" ? null : Number(value); }

export function FoodApp({ active, onSelectModule }: { active: boolean; onSelectModule(module: CaptureModule): void }) {
  const today = toTaipeiDate(new Date());
  const [date, setDate] = useState(today);
  const [local, setLocal] = useState<LocalFood>(() => cache()[today] ?? { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() });
  const [history, setHistory] = useState<FoodRecord[]>([]);
  const [library, setLibrary] = useState<FoodLibraryPayload>(emptyFoodLibrary);
  const [libraryRevision, setLibraryRevision] = useState<number | null>(null);
  const [libraryOpen, setLibraryOpen] = useState(false);
  const [issue, setIssue] = useState(false);
  const dateRef = useRef(date); const localRef = useRef(local); const touch = useRef<number | null>(null);
  const syncDebounceRef = useRef<ReturnType<typeof createDateBoundDebounce<LocalFood>> | null>(null);
  syncDebounceRef.current ??= createDateBoundDebounce<LocalFood>({ delayMs: 800, schedule: (callback, delayMs) => window.setTimeout(callback, delayMs), cancel: (handle) => window.clearTimeout(handle as number) });
  const editable = date === today || date === shiftJournalDate(today, -1);
  const publish = useCallback((targetDate: string, next: LocalFood) => { localRef.current = next; if (targetDate === dateRef.current) setLocal(next); const values = cache(); values[targetDate] = next; persist(values); }, []);
  const sync = useCallback(async (targetDate: string, candidate = localRef.current) => {
    if (!candidate.pending || candidate.conflict || !isFoodPayloadReady(candidate.payload)) return;
    try {
      const response = await fetch("/api/special-records/food", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ journalDate: targetDate, payload: candidate.payload, expectedRevision: candidate.revision, clientUpdatedAt: candidate.clientUpdatedAt }) });
      const result = await response.json(); if (!response.ok) { if (result?.error?.code === "REVISION_CONFLICT") { const current = cache()[targetDate] ?? candidate; publish(targetDate, { ...current, conflict: { cloud: result.record ?? null } }); } setIssue(true); return; }
      const current = cache()[targetDate] ?? candidate; if (current.clientUpdatedAt === candidate.clientUpdatedAt) publish(targetDate, { ...current, revision: result.record?.revision ?? null, pending: false, conflict: undefined }); setIssue(false);
    } catch { setIssue(true); }
  }, [publish]);
  const mutate = useCallback((change: (payload: FoodPayload) => void) => { const payload = structuredClone(localRef.current.payload); change(payload); const next = { ...localRef.current, payload, pending: true, clientUpdatedAt: new Date().toISOString() }; const targetDate = dateRef.current; publish(targetDate, next); syncDebounceRef.current?.queue(targetDate, next, sync); }, [publish, sync]);
  const load = useCallback(async (targetDate: string) => { targetDate = clampRecorderDate(targetDate, today); dateRef.current = targetDate; setDate(targetDate); const cached = cache()[targetDate]; if (cached) { publish(targetDate, cached); if (cached.pending) void sync(targetDate, cached); } try { const response = await fetch(`/api/special-records/food?date=${encodeURIComponent(targetDate)}`, { cache: "no-store" }); const { record } = await response.json() as { record: FoodRecord | null }; if (!cache()[targetDate]?.pending) publish(targetDate, record ? { payload: record.payload, revision: record.revision, pending: false, clientUpdatedAt: record.updatedAt } : { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() }); setIssue(false); } catch { if (!cached) setIssue(true); } }, [publish, sync, today]);
  useEffect(() => { if (!active) return; queueMicrotask(() => void load(dateRef.current)); void fetch("/api/special-records/food", { cache: "no-store" }).then((response) => response.json()).then(({ records }) => setHistory(records ?? [])).catch(() => undefined); void fetch("/api/special-records/food/library", { cache: "no-store" }).then((response) => response.json()).then(({ record }: { record: FoodLibraryRecord | null }) => { setLibrary(record?.payload ?? emptyFoodLibrary()); setLibraryRevision(record?.revision ?? null); }).catch(() => setIssue(true)); }, [active, load]);
  useEffect(() => { const retryPending = () => { for (const [targetDate, candidate] of Object.entries(cache())) if (candidate.pending) void sync(targetDate, candidate); }; const retryVisible = () => { if (document.visibilityState === "visible") retryPending(); }; window.addEventListener("online", retryPending); document.addEventListener("visibilitychange", retryVisible); return () => { window.removeEventListener("online", retryPending); document.removeEventListener("visibilitychange", retryVisible); syncDebounceRef.current?.cancel(); }; }, [sync]);
  const recent = useMemo(() => { const values: FoodLibraryEntry[] = library.entries.filter((entry) => !entry.archived).sort((left, right) => left.order - right.order); for (const record of history) for (const entry of [...record.payload.entries].reverse()) if (!values.some((item) => item.name.toLocaleLowerCase() === entry.name.toLocaleLowerCase())) values.push({ id: entry.libraryEntryId ?? entry.id, name: entry.name, quantity: entry.quantity, unit: entry.unit, calories: entry.calories, proteinGrams: entry.proteinGrams, order: values.length, archived: false }); return values.slice(0, 8); }, [history, library]);
  const totals = local.payload.entries.reduce((value, entry) => ({ calories: value.calories + (entry.calories ?? 0), protein: value.protein + (entry.proteinGrams ?? 0) }), { calories: 0, protein: 0 });
  function add(source?: FoodLibraryEntry) { if (!editable) return; mutate((payload) => payload.entries.push({ id: crypto.randomUUID(), libraryEntryId: source?.id, name: source?.name ?? "", quantity: source?.quantity ?? null, unit: source?.unit ?? "份", calories: source?.calories ?? null, proteinGrams: source?.proteinGrams ?? null, note: "", occurredAt: new Date().toISOString() })); }
  function update(id: string, change: (entry: FoodEntry) => void) { mutate((payload) => { const target = payload.entries.find((entry) => entry.id === id); if (target) change(target); }); }
  async function saveLibrary(next: FoodLibraryPayload) { setLibrary(next); try { const response = await fetch("/api/special-records/food/library", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ payload: next, expectedRevision: libraryRevision }) }); const result = await response.json(); if (!response.ok) { if (result.record) { setLibrary(result.record.payload); setLibraryRevision(result.record.revision); } setIssue(true); return; } setLibrary(result.record.payload); setLibraryRevision(result.record.revision); setIssue(false); } catch { setIssue(true); } }
  function ensureLibrary(entry: FoodEntry) { const name = entry.name.trim(); if (!name || entry.libraryEntryId) return; const existing = library.entries.find((item) => item.name.toLocaleLowerCase() === name.toLocaleLowerCase()); const item = existing ?? { id: crypto.randomUUID(), name, quantity: entry.quantity, unit: entry.unit, calories: entry.calories, proteinGrams: entry.proteinGrams, order: library.entries.length, archived: false }; if (!existing) void saveLibrary({ ...library, entries: [...library.entries, item] }); update(entry.id, (target) => { target.libraryEntryId = item.id; }); }
  function used(entry: FoodLibraryEntry) { return history.some((record) => record.payload.entries.some((food) => food.libraryEntryId === entry.id || (!food.libraryEntryId && food.name.toLocaleLowerCase() === entry.name.toLocaleLowerCase()))); }
  function useCloudVersion() { const cloud = localRef.current.conflict?.cloud; const next: LocalFood = cloud ? { payload: cloud.payload, revision: cloud.revision, pending: false, clientUpdatedAt: cloud.updatedAt } : { payload: emptyFoodPayload(), revision: null, pending: false, clientUpdatedAt: new Date().toISOString() }; publish(date, next); setIssue(false); }
  function keepLocalVersion() { const current = localRef.current; if (!current.conflict) return; const { conflict, ...withoutConflict } = current; const next = rebaseConflictCandidate(withoutConflict, conflict.cloud?.revision ?? null); publish(date, next); setIssue(false); void sync(date, next); }
  if (!active) return null;
  return <main className="foodShell" onPointerDown={(event) => { if (event.pointerType === "touch") touch.current = event.clientX; }} onPointerUp={(event) => { if (event.pointerType !== "touch" || touch.current === null) return; const delta = event.clientX - touch.current; touch.current = null; if (Math.abs(delta) > 70) void load(shiftJournalDate(date, delta > 0 ? -1 : 1)); }}>
    <header className="foodToolbar"><label>{date.slice(5).replace("-", ".")}<input type="date" max={today} value={date} onChange={(event) => void load(event.target.value)} /></label><div><strong>{totals.calories}</strong><input aria-label="熱量目標" type="number" value={local.payload.calorieTarget ?? ""} disabled={!editable} onChange={(event) => mutate((payload) => { payload.calorieTarget = number(event.target.value); })} /></div><div><strong>{totals.protein}g</strong><input aria-label="蛋白質目標" type="number" value={local.payload.proteinTargetGrams ?? ""} disabled={!editable} onChange={(event) => mutate((payload) => { payload.proteinTargetGrams = number(event.target.value); })} /></div><span>{issue ? "!" : local.pending ? "·" : ""}</span></header>
    {local.conflict ? <div className="specialConflict" role="alert"><span>版本</span><button type="button" onClick={useCloudVersion}>雲端</button><button type="button" onClick={keepLocalVersion}>本機</button></div> : null}
    <section className="foodBody">
      <div className="recentFoods">{recent.map((entry) => <button key={entry.id} disabled={!editable} onClick={() => add(entry)}>{entry.name}</button>)}<button disabled={!editable} onClick={() => add()}>＋</button><button onClick={() => setLibraryOpen((open) => !open)}>⋯</button></div>
      {libraryOpen ? <div className="foodLibrary">{library.entries.slice().sort((left, right) => left.order - right.order).map((entry, index, entries) => <div key={entry.id} className={entry.archived ? "archived" : ""}><input value={entry.name} onChange={(event) => setLibrary((current) => ({ ...current, entries: current.entries.map((item) => item.id === entry.id ? { ...item, name: event.target.value } : item) }))} onBlur={(event) => { const name = event.target.value.trim(); if (name) void saveLibrary({ ...library, entries: library.entries.map((item) => item.id === entry.id ? { ...item, name } : item) }); }} /><button disabled={index === 0} onClick={() => { const next = entries.slice(); [next[index - 1], next[index]] = [next[index], next[index - 1]]; void saveLibrary({ ...library, entries: next.map((item, order) => ({ ...item, order })) }); }}>↑</button><button disabled={index === entries.length - 1} onClick={() => { const next = entries.slice(); [next[index], next[index + 1]] = [next[index + 1], next[index]]; void saveLibrary({ ...library, entries: next.map((item, order) => ({ ...item, order })) }); }}>↓</button><button onClick={() => void saveLibrary({ ...library, entries: library.entries.map((item) => item.id === entry.id ? { ...item, archived: !item.archived } : item) })}>{entry.archived ? "◇" : "—"}</button>{!used(entry) ? <button onClick={() => void saveLibrary({ ...library, entries: library.entries.filter((item) => item.id !== entry.id).map((item, order) => ({ ...item, order })) })}>×</button> : <span />}</div>)}</div> : null}
      {local.payload.entries.map((entry) => <article key={entry.id} className="foodEntry"><div><input className="foodName" placeholder="食物" value={entry.name} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.name = event.target.value; })} onBlur={() => ensureLibrary(entry)} /><time>{new Intl.DateTimeFormat("zh-TW", { timeZone: "Asia/Taipei", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(entry.occurredAt))}</time>{editable ? <button aria-label="移除" onClick={() => mutate((payload) => { payload.entries = payload.entries.filter((item) => item.id !== entry.id); })}>×</button> : null}</div><div className="foodFields"><label>量<input type="number" inputMode="decimal" value={entry.quantity ?? ""} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.quantity = number(event.target.value); })} /></label><label>單位<input value={entry.unit} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.unit = event.target.value; })} /></label><label>kcal<input type="number" inputMode="decimal" value={entry.calories ?? ""} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.calories = number(event.target.value); })} /></label><label>蛋白質 g<input type="number" inputMode="decimal" value={entry.proteinGrams ?? ""} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.proteinGrams = number(event.target.value); })} /></label></div><textarea placeholder="註記" value={entry.note} disabled={!editable} onChange={(event) => update(entry.id, (item) => { item.note = event.target.value; })} /></article>)}
    </section><ModuleRail active="food" onSelect={onSelectModule} />
  </main>;
}
