import { getMongoClient, getMongoDatabaseName } from "./mongodb.ts";
import type { FoodLibraryRecord, FoodLibrarySaveInput } from "./food-library.ts";
type Document = Omit<FoodLibraryRecord, "id"> & { _id: "food:library" };
type Collection = { findOne(filter: Partial<Document>): Promise<Document | null>; updateOne(filter: Partial<Document>, update: { $setOnInsert: Document }, options: { upsert: true }): Promise<unknown>; findOneAndUpdate(filter: Partial<Document>, update: { $set: Partial<Document>; $inc: { revision: number } }, options: { returnDocument: "after" }): Promise<Document | null> };
function record(document: Document): FoodLibraryRecord { const { _id, ...rest } = document; return { id: _id, ...rest }; }
async function collection(): Promise<Collection> { const client = await getMongoClient(); return client.db(getMongoDatabaseName()).collection<Document>("specialRecorderSettings"); }
export class FoodLibraryStore {
  private readonly getCollection: () => Promise<Collection>; private readonly now: () => Date;
  constructor(getCollection: () => Promise<Collection> = collection, now: () => Date = () => new Date()) { this.getCollection = getCollection; this.now = now; }
  async get() { const found = await (await this.getCollection()).findOne({ _id: "food:library", moduleId: "food" }); return found ? record(found) : null; }
  async save(input: FoodLibrarySaveInput): Promise<{ kind: "created" | "updated"; record: FoodLibraryRecord } | { kind: "conflict"; record: FoodLibraryRecord | null }> { const target = await this.getCollection(); const current = await target.findOne({ _id: "food:library", moduleId: "food" }); const timestamp = this.now().toISOString(); if (!current) { if (input.expectedRevision !== null) return { kind: "conflict", record: null }; const document: Document = { _id: "food:library", moduleId: "food", payload: input.payload, revision: 0, createdAt: timestamp, updatedAt: timestamp }; await target.updateOne({ _id: document._id }, { $setOnInsert: document }, { upsert: true }); const stored = await target.findOne({ _id: document._id, moduleId: "food" }); return stored && stored.revision === 0 && JSON.stringify(stored.payload) === JSON.stringify(input.payload) ? { kind: "created", record: record(stored) } : { kind: "conflict", record: stored ? record(stored) : null }; } if (input.expectedRevision !== current.revision) return { kind: "conflict", record: record(current) }; const updated = await target.findOneAndUpdate({ _id: current._id, moduleId: "food", revision: current.revision }, { $set: { payload: input.payload, updatedAt: timestamp }, $inc: { revision: 1 } }, { returnDocument: "after" }); return updated ? { kind: "updated", record: record(updated) } : { kind: "conflict", record: await this.get() }; }
}
export const foodLibraryStore = new FoodLibraryStore();
